[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --only=production && npm install --save-dev @nestjs/cli typescript && npx prisma generate && npx nest build"

[deploy]
startCommand = "cd backend && npm run start:prod"
healthcheckPath = "/health/live"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }
