[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = [
  "npm install --save-dev @nestjs/cli",
  "npx prisma generate",
  "npx nest build"
]

[start]
cmd = "npm run start:prod"
